# 1. keggle
importing data from keggle and importing pandas library

In [1]:
import pandas as pd
import os
os.environ['KAGGLEHUB_CACHE'] = '/home/zeus/programming/python/data'

import kagglehub

# Download latest version
path = kagglehub.dataset_download("themrityunjaypathak/pandas-practice-dataset")

print("Path to dataset files:", path)

/home/zeus/programming/python/.venv/lib64/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /home/zeus/programming/python/data/datasets/themrityunjaypathak/pandas-practice-dataset/versions/1

# 2. DataFrames

In [2]:
dc1 = {
    'ID' : [1,2,3],
    'Name' : ['A', 'B', 'C'],
    'Age' : [21,22,23]
    }

dc2 = {
    'ID' : [3, 5, 4],
    'Name' : ['C', 'D', 'E'],
    'Age' : [23, 24, 25]
}

df1 = pd.DataFrame(dc1)
df2 = pd.DataFrame(dc2)
print(df1)
print(df2)

   ID Name  Age
0   1    A   21
1   2    B   22
2   3    C   23
   ID Name  Age
0   3    C   23
1   5    D   24
2   4    E   25

# 3. Concatenating DataFrames

In [3]:
result = pd.concat([df1, df2], ignore_index=True)
print(result)

   ID Name  Age
0   1    A   21
1   2    B   22
2   3    C   23
3   3    C   23
4   5    D   24
5   4    E   25

# 4. Dropping Duplicates

In [4]:
cleanResult = result.drop_duplicates()
print(cleanResult)

   ID Name  Age
0   1    A   21
1   2    B   22
2   3    C   23
4   5    D   24
5   4    E   25

# 5. Sorting of values

In [5]:
cleanResult = cleanResult.sort_values(by= 'ID')
print(cleanResult)

   ID Name  Age
0   1    A   21
1   2    B   22
2   3    C   23
5   4    E   25
4   5    D   24

In [6]:
n = int(input("input number: "))
i = 0
while(1):
    print(n*i)
    i += 1
    if(n*i > 40):
        break

0
4
8
12
16
20
24
28
32
36
40

In [7]:
value = 1
age = 90 if value == 1 else 80 if value > 1 else 38

In [8]:
a = 10
b = 5
print(a > 5 and b < 10) 
print(a < 5 or b < 10) 
print(not(a==10))

True
True
False

# 6. Reading CSV files

In [9]:
df3 = pd.read_csv('/home/zeus/programming/python/data/data.csv')
print(df3)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

# 7. Changing data at specific location using .iat

In [10]:
df3.iat[26, 1] = '\'2020/12/26\''
df3.iat[22, 1] = '\'2020/12/22\''
df3.iat[18, 4] = df3['Calories'].mean()
df3.iat[28, 4] = df3['Calories'].mean()
df3.iat[7,0] = 45

In [11]:
print(df3)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7         45  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
22        45  '2020/12/22'    100       119    282.00
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60  '2020/12/26'    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

In [12]:
for i in range(3):
    for j in range(3):
        print("*", end="")
    print()

***
***
***

In [13]:
price = 100
gst_rate = 0.18
totoal_price = price + (price * gst_rate)

In [14]:
for i in range(1, 10):
    if(i == 6): continue
    print(i)

1
2
3
4
5
7
8
9

In [15]:
marks = int(input("enter marks: "))
print('A') if marks >= 90 else print('B') if marks >= 75 else print('C') if marks >= 60 else print('D') if marks >= 35 else print("fail")

fail

In [16]:
i = 0
while(i < 6):
    print(i * 7)
    i += 1

0
7
14
21
28
35

In [17]:
for i in range(51):
    if(i % 5 == 0):
        print(i)

0
5
10
15
20
25
30
35
40
45
50

In [18]:
n = int(input('enter nubmer: '))
print('positive') if n > 0 else print('zero') if n == 0 else print('negative')

positive

In [19]:
data = pd.DataFrame({
    'name' : ['vansh', 'aman', 'gurleen'],
    'age' : [21, 21, 21],
    'address' : ['zirakpur', 'mohali', 'chandigarh']
})

print(data)

      name  age     address
0    vansh   21    zirakpur
1     aman   21      mohali
2  gurleen   21  chandigarh

In [20]:
data[['name', 'age']]

      name  age
0    vansh   21
1     aman   21
2  gurleen   21

In [21]:
count = 0 
for i in range(4):
    for j in range(4,0 ,-1):
        if i + j == i * j:
            count += 1
print(count)

1

In [22]:
placement = pd.read_csv('/home/zeus/programming/python/data/Placement_Data - Placement_Data.csv')

In [23]:
placement

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

# 8. Structure of the DataFrame

In [24]:
placement.shape

(215, 15)

# 9. head() to print the first 5 or specified no. of rows

In [25]:
placement.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

# 10. tail() same as head

In [26]:
placement.tail()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
210,211,M,80.6,Others,82.0,Others,Commerce,77.6,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.0,Others,60.0,Others,Science,72.0,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.0,Others,67.0,Others,Commerce,73.0,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.0,Others,66.0,Others,Commerce,58.0,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.0,Central,58.0,Others,Science,53.0,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

# 11. List of all the columns of the DataFrame

In [27]:
placement.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='str')

# 12. Information about data in the DataFrame

In [28]:
placement.info()

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    str
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    str
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    str
 6   hsc_s           215 non-null    str
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    str
 9   workex          215 non-null    str
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    str
 12  mba_p           215 non-null    float64
 13  status          215 non-null    str
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), str(8)
memory usage: 25.3 KB

# 13. Tells us whether there exit NULL values or not

In [29]:
placement.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

# 14. Average

In [30]:
placement['ssc_p'].mean()

np.float64(67.30339534883721)

In [31]:
max(placement['ssc_p'])

89.4

# 15. To display the person with highest marks

In [32]:
placement[placement['ssc_p'] == placement['ssc_p'].max()]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
145,146,M,89.4,Others,65.66,Others,Science,71.25,Sci&Tech,No,72.0,Mkt&HR,63.23,Placed,400000.0

# 16. To display how many people got placed

In [33]:
placement[placement['status'] == 'Placed']['status'].count()

np.int64(148)

In [34]:

placement[placement['status'] == 'Not Placed']['status'].count()

np.int64(67)

In [35]:
placement[placement['status'] == 'Placed']['degree_t'].value_counts().head(1)

degree_t
Comm&Mgmt    102
Name: count, dtype: int64

In [36]:
placement['degree_t'].nunique()

3

In [37]:
placement['degree_t'].unique()

<StringArray>
['Sci&Tech', 'Comm&Mgmt', 'Others']
Length: 3, dtype: str

In [38]:
placement[['ssc_p', 'hsc_p', 'degree_p']].corr()
placement.drop(columns=['sl_no'], inplace= True)

In [39]:
placement

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [40]:
placement['salary'].isnull().value_counts()

salary
False    148
True      67
Name: count, dtype: int64

In [41]:
salary_median = placement['salary'].median()
placement.fillna(salary_median, inplace=True)

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,265000.0
4,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,265000.0

In [42]:
placement['salary'].mean()

np.float64(281283.72093023255)

In [43]:

placement.duplicated().value_counts()

False    215
Name: count, dtype: int64

In [44]:
import pandas as pd
age = pd.Series([21, 19, 21, 20], index=['vansh', 'anshul', 'gurleen', 'rishit'])
print(age)
print(age.mean())
print(age.std())
print(round(age.std(), 2))

print(age[['rishit']])

vansh      21
anshul     19
gurleen    21
rishit     20
dtype: int64
20.25
0.9574271077563381
0.96
rishit    20
dtype: int64

In [45]:
df = {
    'Name': ['vansh', 'adhiraj', 'shayan', 'aman', 'kartik', 'vidit'],
    'class': [12, 11, 11, 12, 12, 11],
    'stream': ['Arts', 'Arts', 'Science', 'IT', 'Science', 'Science'],
    'percentage': [94, 83, 89, 88, 84, 98]
}
frame = pd.DataFrame(df)
print(frame)
print(frame.describe())

      Name  class   stream  percentage
0    vansh     12     Arts          94
1  adhiraj     11     Arts          83
2   shayan     11  Science          89
3     aman     12       IT          88
4   kartik     12  Science          84
5    vidit     11  Science          98
           class  percentage
count   6.000000    6.000000
mean   11.500000   89.333333
std     0.547723    5.785038
min    11.000000   83.000000
25%    11.000000   85.000000
50%    11.500000   88.500000
75%    12.000000   92.750000
max    12.000000   98.000000

In [91]:
import numpy as np
sales = {
    'order_id' : [1,2,3,4,5,6,7,8,9,10],
    'region' : ['East','West','East','North','West', 'East', 'North', 'West','East','North'],
    'product' : ['A','B','A','C','B','C','A','A','B','C'],
    'quantity' : [10, 5, 8, 12, 7, np.nan, 9, 4, 11, np.nan],
    'unit_price' : [100, 200, 100, 150, 200, 150, 100, 100, 200, 150],
    'date' : pd.to_datetime([
        "2024-01-05","2024-01-07","2024-02-10","2024-02-15","2024-03-01","2024-03-12","2024-04-02","2024-04-18","2024-05-05","2024-05-20"
    ])
}
sales

{'order_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 'region': ['East',
  'West',
  'East',
  'North',
  'West',
  'East',
  'North',
  'West',
  'East',
  'North'],
 'product': ['A', 'B', 'A', 'C', 'B', 'C', 'A', 'A', 'B', 'C'],
 'quantity': [10, 5, 8, 12, 7, nan, 9, 4, 11, nan],
 'unit_price': [100, 200, 100, 150, 200, 150, 100, 100, 200, 150],
 'date': DatetimeIndex(['2024-01-05', '2024-01-07', '2024-02-10', '2024-02-15',
                '2024-03-01', '2024-03-12', '2024-04-02', '2024-04-18',
                '2024-05-05', '2024-05-20'],
               dtype='datetime64[us]', freq=None)}

In [92]:
df = pd.DataFrame(sales)

In [93]:
df

   order_id region product  quantity  unit_price       date
0         1   East       A      10.0         100 2024-01-05
1         2   West       B       5.0         200 2024-01-07
2         3   East       A       8.0         100 2024-02-10
3         4  North       C      12.0         150 2024-02-15
4         5   West       B       7.0         200 2024-03-01
5         6   East       C       NaN         150 2024-03-12
6         7  North       A       9.0         100 2024-04-02
7         8   West       A       4.0         100 2024-04-18
8         9   East       B      11.0         200 2024-05-05
9        10  North       C       NaN         150 2024-05-20

In [95]:
averageQuantity = df['quantity'].mean()
df.loc[df['quantity'] > averageQuantity]

   order_id region product  quantity  unit_price       date
0         1   East       A      10.0         100 2024-01-05
3         4  North       C      12.0         150 2024-02-15
6         7  North       A       9.0         100 2024-04-02
8         9   East       B      11.0         200 2024-05-05

In [136]:
df.iloc[-3:, df.columns.get_indexer(['product', 'unit_price'])]

  product  unit_price
7       A         100
8       B         200
9       C         150

In [ ]:
df.loc[df.index[-3:], ['product', 'unit_price']]

  product  unit_price
7       A         100
8       B         200
9       C         150

In [135]:
df.loc[[7,8,9], ['product', 'unit_price']]

  product  unit_price
7       A         100
8       B         200
9       C         150